FROM node:12.18.2-slim

RUN set -x \
    && apt-get update \
    && apt-get install -y build-essential git --no-install-recommends --no-install-suggests \
    && apt-get install -y python libcurl4-openssl-dev libsecret-1-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN npm install -g @angular/cli @angular-devkit/build-angular

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
ENV APP_DIR /fe
RUN mkdir -p ${APP_DIR}
WORKDIR ${APP_DIR}
COPY /fe ${APP_DIR}

RUN yarn install --frozen-lockfile
