FROM node:latest
WORKDIR /usr/app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN apt-get update && apt-get install -y netcat-openbsd
COPY wait-for-it.sh /usr/app/wait-for-it.sh  
EXPOSE 5000
CMD ["./wait-for-it.sh", "mongo:27017", "--", "npm", "start"]
